### PR TITLE
Allow every entry to be rolled only once.

### PR DESCRIPTION
**Pull request by noccu**
Saves and loads between sessions, can be reset.
Equality! <s>but RNGesus still shits on you</s>

### CODE REVIEW

**Review by shfg-wwd — COMMENTED** [review]
Ok, I can't use my computer right now but I'd like to change the _\n_ when you join the data with a `<br>` tag.

Also it would be nice to explain in the page that it only rolls each waifu once as a note for clarity. 

I might do it in the evening but I'm letting you know in case you want to change it. 

A question, is there a way to test the page locally? Do you seve it with nodejs or something? It's my first time using github pages.

**Comment by noccu** [comment]
There is any number of ways of course. I'm using a small server extension/app for chrome to test.
I'll have a look later, if you don't do it first. What's the reason for the \n change though?

**Comment by shfg-wwd** [comment]
Thanks I found how. Its using jekyll.

>What's the reason for the \n change though?

I suspect it's the cause of a small bug on firefox that sometimes breaks the lines improperly. But I'm not sure. It's more correct for html anyways

**Comment by noccu** [comment]
Oh I see, I only tested chrome on pc. Adjusted as per your comment.

**Pull request merged**
